name: Deploy page
on: push
jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: deploy
        run: |
           npm run deploy